import Head from 'next/head'
// Import Swiper React components
import { Navigation, Pagination, Scrollbar, A11y, Autoplay } from 'swiper';

import { Swiper, SwiperSlide } from 'swiper/react';

// Import Swiper styles
import 'swiper/css';
import 'swiper/css/navigation';
import 'swiper/css/pagination';
import 'swiper/css/scrollbar';
import 'swiper/css/autoplay';

import pic1 from '../../public/img/pic1.jpg';
import pic2 from '../../public/img/pic2.jpg';
import pic3 from '../../public/img/pic3.webp';
import pic4 from '../../public/img/pic4.webp';
import Image from 'next/image';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <Swiper
            // install Swiper modules
            modules={[Navigation, Pagination, Scrollbar, A11y, Autoplay]}
            spaceBetween={5}
            slidesPerView={1}
            autoplay={{ 'delay': 5000 }}
            navigation
            pagination={{ clickable: true }}
            scrollbar={true}
            onSwiper={(swiper) => console.log(swiper)}
            onSlideChange={() => console.log('slide change')}
          >
            <SwiperSlide><div className='swiper-div'><Image src={pic1} alt='pic1'/></div></SwiperSlide>
            <SwiperSlide><div className='swiper-div'><Image src={pic2} alt='pic2'/></div></SwiperSlide>
            <SwiperSlide><div className='swiper-div'><Image src={pic3} alt='pic3'/></div></SwiperSlide>
            <SwiperSlide><div className='swiper-div'><Image src={pic4} alt='pic4'/></div></SwiperSlide>
          </Swiper>
          <div className='parent'>
            <p className='text1'>text-1</p>
          </div>
          <p className='text2'>text-2</p>
        </div>
      </main>
    </>
  )
}
