import Head from 'next/head'
// Import Swiper React components
import { Navigation, Pagination, Scrollbar, A11y, Autoplay } from 'swiper';

import { Swiper, SwiperSlide } from 'swiper/react';

// Import Swiper styles
import 'swiper/css';
import 'swiper/css/navigation';
import 'swiper/css/pagination';
import 'swiper/css/scrollbar';
import 'swiper/css/autoplay';

import pic1 from '../../public/img/pic1.jpg';
import pic2 from '../../public/img/pic2.jpg';
import pic3 from '../../public/img/pic3.webp';
import pic4 from '../../public/img/pic4.webp';
import Image from 'next/image';

export default function Home() {
  const contents=[
    {
      picture:pic1,
      text:'今こそpic1'
    },
    {
      picture:pic2,
      text:'明日へpic2'
    },
    {
      picture:pic3,
      text:'更なるpic3'
    },
    {
      picture:pic4,
      text:'未来にpic4'
    },
  ];
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
      </Head>
      <main>
        <div>
          <Swiper
            // install Swiper modules
            modules={[Navigation, Pagination, Scrollbar, A11y, Autoplay]}
            spaceBetween={5}
            slidesPerView={1}
            autoplay={{ 'delay': 5000 }}
            navigation
            pagination={{ clickable: true }}
            scrollbar={true}
            onSwiper={(swiper) => console.log(swiper)}
            onSlideChange={() => console.log('slide change')}
          >
            {contents.map((content,index)=>(
            <SwiperSlide key={index}><div className='swiper-div'><Image src={content.picture} alt='picture' /><p>{content.text}</p></div></SwiperSlide>              
            ))}
          </Swiper>
        </div>
      </main>
    </>
  )
}
