import Head from 'next/head'

export default function Page2() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="stylesheet" href="http://localhost:test2/style.css" /> */}
      </Head>
      <main>
        <div>
          <p>This is Page-2</p>
        </div>
      </main>
    </>
  )
}
